Feat/add endpoint
codeforjapan/JibungotoPlanet-backend pull request #76
Opened 2023-01-07 09:53 UTC by ayuki-joto

他のエンドポイントの追加

2023-01-08 09:00 UTC, ayuki-joto commented
これで一通り移行周り完了したはず

2023-01-08 09:00 UTC, ayuki-joto commented
データ入れて検証して問題なければリリースできるかと思います

2023-01-08 15:11 UTC, naoji3x commented
profileTableはshareIdでも検索できるようにprofilesByShareIdをGSI(グローバルセカンダリインデックス)として付与した記憶があります（schema.graphqlの202行目になります）。DynamodbStackでaddLocalSecondaryIndexを使ってGSIを付与する必要があるのではないでしょうか？

2023-01-10 04:28 UTC, ushios approved these changes
気持ちコメントしましたけど、そんなに気にしなくていいと思います

2023-01-10 04:28 UTC, ushios commented on cdk/lib/api-gateway-stack.ts
> +
あんまり説明するほどの合理的な理由はないけど、この辺りのリソースをstack分けておく方が好きです。

2023-01-10 04:28 UTC, ushios commented on cdk/lib/dynamodb-stack.ts
>      })
この辺り、ごちゃっとしちゃうから、オブジェクトの配列作って、ループさせてTable作る方が後々楽だと思います。

2023-01-10 10:28 UTC, ayuki-joto commented on cdk/lib/api-gateway-stack.ts
> +
分けました！

2023-01-10 10:30 UTC, ayuki-joto commented on cdk/lib/dynamodb-stack.ts
>      })
一旦書き換えてみました！

2023-01-10 10:38 UTC, ushios requested changes
ちょっと気になったやつ IXxxXxxx を活用した方がよさそう。

2023-01-10 10:38 UTC, ushios commented on cdk/lib/api-gateway-stack.ts
> +  public readonly api: RestApi
外部に出すのは、今後のスタック分けとかにも影響するので本当はArnを書き出して、fromArn で別スタックで作成しなおすとかの方がいいけど、せめて IRestApiとかにしておいた方がいいです

https://docs.aws.amazon.com/cdk/api/v1/docs/@aws-cdk_aws-apigateway.IRestApi.html

2023-01-10 10:38 UTC, ushios commented on cdk/lib/dynamodb-stack.ts
> +    ]
ここ配列じゃなくて、オブジェクトにして、オブジェクトのkeyをoption とかparameterとかにしたら、重複がなくなっていいと思います。
（その上でkeyをオブジェクトに持たせるのもありだと思います。）

2023-01-10 10:38 UTC, ushios commented on cdk/lib/share-stack.ts
> +  public readonly lambda: NodejsFunction
これもIFunctionかな・・・？違うかも？

2023-01-10 14:29 UTC, ayuki-joto commented on cdk/lib/api-gateway-stack.ts
> +  public readonly api: RestApi
IRestApiだと型が合わなかったので、IDomainNameを使うようにして対応しました

2023-01-10 14:30 UTC, ayuki-joto commented on cdk/lib/dynamodb-stack.ts
> +    ]
やってみました
[key: string]: でkeyの型定義してもthis[`${ key }Table`]のエラーが消えないので@ts-ignore入れてます

2023-01-10 14:30 UTC, ayuki-joto commented on cdk/lib/share-stack.ts
> +  public readonly lambda: NodejsFunction
対応しました！

2023-01-11 00:41 UTC, ushios approved these changes

2023-01-11 05:08 UTC, merged